
-- Generated by ORDS REST Data Services 18.4.0.r3541002
-- Schema: AIO  Date: Jue Jun 12 07:31:18 2025 
--

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'AIO',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'aio',
      p_auto_rest_auth      => FALSE);
    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'api',
      p_base_path      => '/api/',
      p_items_per_page => 1000,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'api',
      p_pattern        => 'empresas/todas',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'api',
      p_pattern        => 'empresas/todas',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select emp_id as id,
    emp_nombre as nombre,
    (select nvl(sum(nvl(equ_usado,0)),0)
        from equipos
        where equ_emp = EMP_ID) as usado,
        EMP_CAPACIDAD as capacidad,
       ((select nvl(sum(nvl(equ_usado,0)),0)
        from equipos
        where equ_emp = EMP_ID)/EMP_CAPACIDAD)*100 as porcentaje,
        CASE 
            WHEN EXISTS (
                select ''x'' from equipos
                where equ_emp = emp_id
                    and equ_estado is not null
                    and upper(equ_estado) <> ''CORRECTO''
            )
            THEN ''ERROR''
            ELSE ''CORRECTO''
        END AS estado
from clientes, empresas
where cli_id = emp_cliente
    and upper(cli_email) = upper(:email)
    and toolkit.desencriptar(cli_clave,''AIO987654'') = :clave');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'api',
      p_pattern            => 'empresas/todas',
      p_method             => 'GET',
      p_name               => 'email',
      p_bind_variable_name => 'email',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'api',
      p_pattern            => 'empresas/todas',
      p_method             => 'GET',
      p_name               => 'clave',
      p_bind_variable_name => 'clave',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'api',
      p_pattern        => 'equipos/licencia',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'api',
      p_pattern        => 'equipos/licencia',
      p_method         => 'GET',
      p_source_type    => 'json/query;type=single',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select equ_nombre as nombre,
    emp_nombre as empresa,
    nvl(equ_usado,0) as usado,
    nvl(equ_capacidad,nvl(emp_capacidad,0)) as capacidad,
    equ_ip as ip,
    equ_ubicacion as ubicacion,
    equ_cargo as cargo,
    equ_descripcion as descripcion,
    equ_estado as estado,
    equ_activo as activo
from equipos, empresas
where equ_emp = emp_id
    and equ_licencia = :licencia');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'api',
      p_pattern            => 'equipos/licencia',
      p_method             => 'GET',
      p_name               => 'licencia',
      p_bind_variable_name => 'licencia',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'api',
      p_pattern        => 'equipos/todos',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'api',
      p_pattern        => 'equipos/todos',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select equ_licencia as licencia,
    equ_nombre as nombre,
    emp_nombre as empresa,
    nvl(equ_usado,0) as usado,
    nvl(equ_capacidad,nvl(emp_capacidad,0)) as capacidad,
    equ_ip as ip,
    equ_ubicacion as ubicacion,
    equ_estado as estado,
    equ_activo as activo
from equipos, empresas, clientes
where equ_emp = emp_id
    and cli_id = emp_cliente
    and upper(cli_email) = upper(:email)
    and toolkit.desencriptar(cli_clave,''AIO987654'') = :clave');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'api',
      p_pattern            => 'equipos/todos',
      p_method             => 'GET',
      p_name               => 'email',
      p_bind_variable_name => 'email',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'api',
      p_pattern            => 'equipos/todos',
      p_method             => 'GET',
      p_name               => 'clave',
      p_bind_variable_name => 'clave',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'api',
      p_pattern        => 'clientes/registrar',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'api',
      p_pattern        => 'clientes/registrar',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'DECLARE
    v_count     number;
    v_emp_capacidad   clientes.cli_id%TYPE := clientes_seq.nextval;
    v_empresa   empresas.emp_id%TYPE := empresas_seq.nextval;
    v_licencia  equipos.equ_licencia%TYPE := generar_licencia();
BEGIN

    -- Comprueba si el correo esta en uso
    select count(''x'') into v_count from clientes where cli_email = :email;

    IF v_count = 0 THEN
        :licencia := v_licencia;

        INSERT INTO CLIENTES (
            CLI_ID, CLI_DNI, CLI_NOMBRE, CLI_CLAVE,
            CLI_ACTIVO, CLI_EMAIL, CLI_TELEFONO,
            CLI_DIRECCION, CLI_TIPO
        ) VALUES (
            v_cliente,
            :dni,
            :nombre,
            toolkit.encriptar(:clave,''AIO987654''),
            ''S'',
            :email,
            :telefono,
            :direccion,
            decode(upper(:tipo),''E'',''E'',''A'')
        );

        INSERT INTO EMPRESAS (EMP_ID, EMP_CLIENTE, EMP_NOMBRE, EMP_CAPACIDAD) VALUES (
            v_empresa,
            v_cliente,
            :empresa,
            :capacidad
        );

        INSERT INTO EQUIPOS (
            EQU_ID, EQU_EMP, EQU_NOMBRE, EQU_IP,
            EQU_UBICACION, EQU_ACTIVO, EQU_ESTADO,
            EQU_LICENCIA, EQU_USADO, EQU_CAPACIDAD
        ) VALUES (
            equipos_seq.nextval,
            v_empresa,
            :equipo,
            :ip,
            :ubicacion,
            ''S'',
            ''CORRECTO'',
            v_licencia,
            0,
            :capacidad
        );
    ELSE
        :error := ''Este correo esta en uso'';
    END IF;

    
END;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'api',
      p_pattern            => 'clientes/registrar',
      p_method             => 'POST',
      p_name               => 'nombre',
      p_bind_variable_name => 'nombre',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'api',
      p_pattern            => 'clientes/registrar',
      p_method             => 'POST',
      p_name               => 'clave',
      p_bind_variable_name => 'clave',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'api',
      p_pattern            => 'clientes/registrar',
      p_method             => 'POST',
      p_name               => 'email',
      p_bind_variable_name => 'email',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'api',
      p_pattern            => 'clientes/registrar',
      p_method             => 'POST',
      p_name               => 'dni',
      p_bind_variable_name => 'dni',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'api',
      p_pattern            => 'clientes/registrar',
      p_method             => 'POST',
      p_name               => 'telefono',
      p_bind_variable_name => 'telefono',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'api',
      p_pattern            => 'clientes/registrar',
      p_method             => 'POST',
      p_name               => 'direccion',
      p_bind_variable_name => 'direccion',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'api',
      p_pattern            => 'clientes/registrar',
      p_method             => 'POST',
      p_name               => 'tipo',
      p_bind_variable_name => 'tipo',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'api',
      p_pattern            => 'clientes/registrar',
      p_method             => 'POST',
      p_name               => 'licencia',
      p_bind_variable_name => 'licencia',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'api',
      p_pattern            => 'clientes/registrar',
      p_method             => 'POST',
      p_name               => 'empresa',
      p_bind_variable_name => 'empresa',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'api',
      p_pattern            => 'clientes/registrar',
      p_method             => 'POST',
      p_name               => 'capacidad',
      p_bind_variable_name => 'capacidad',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'api',
      p_pattern            => 'clientes/registrar',
      p_method             => 'POST',
      p_name               => 'ip',
      p_bind_variable_name => 'ip',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'api',
      p_pattern            => 'clientes/registrar',
      p_method             => 'POST',
      p_name               => 'ubicacion',
      p_bind_variable_name => 'ubicacion',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'api',
      p_pattern            => 'clientes/registrar',
      p_method             => 'POST',
      p_name               => 'error',
      p_bind_variable_name => 'error',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'api',
      p_pattern        => 'equipos/registrar',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'api',
      p_pattern        => 'equipos/registrar',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'DECLARE
    v_count         number;
    v_licencia      varchar2(100) := generar_licencia();
    v_capacidad_emp number;
    v_emp_id        number;
    v_usado_emp     number;
BEGIN
    -- Comprueba si el usuario existe
    select count(''x'') into v_count from clientes where upper(cli_email) = upper(:email) and toolkit.desencriptar(cli_clave,''AIO987654'') = :clave;

    IF v_count > 0 THEN    

        -- Sacar datos de la empresa
        IF :empresa is null THEN
            select emp_id, emp_capacidad into v_emp_id, v_capacidad_emp
            from clientes, empresas
            where cli_id = emp_cliente
                and upper(cli_email) = upper(:email) and toolkit.desencriptar(cli_clave,''AIO987654'') = :clave
                and rownum = 1;
        ELSE    
            v_emp_id := :empresa;
            select emp_capacidad into v_capacidad_emp
            from empresas
            where emp_id = v_emp_id;
        END IF;

        -- Comprobar capacidad de empresa
        select nvl(sum(nvl(equ_usado,0)),0) + nvl(:usado,0) into v_usado_emp
        from equipos
        where equ_emp = v_emp_id;

        IF nvl(:usado,0) <= nvl(:capacidad,v_capacidad_emp) and v_usado_emp <= v_capacidad_emp THEN
            -- Crear equipo
            :licencia := v_licencia;        
            INSERT INTO EQUIPOS (EQU_ID, EQU_EMP, EQU_NOMBRE, EQU_IP, EQU_UBICACION, EQU_ACTIVO, EQU_ESTADO, EQU_LICENCIA, EQU_USADO, EQU_CAPACIDAD
            ) VALUES (
                EQUIPOS_SEQ.nextval,     -- EQU_ID
                v_emp_id,                -- EQU_EMP
                nvl(:nombre,''MI PC''),    -- EQU_NOMBRE
                :ip,                     -- EQU_IP
                :ubicacion,              -- EQU_UBICACION
                :cargo,                  -- EQU_CARGO
                :descripcion,            -- EQU_DESCRIPCION
                ''S'',                     -- EQU_ACTIVO
                nvl(:estado,''CORRECTO''), -- EQU_ESTADO
                v_licencia,              -- EQU_LICENCIA
                nvl(:usado,0),           -- EQU_USADO
                nvl(:capacidad,100)      -- EQU_CAPACIDAD
            );
        ELSE
            :error := ''Capacidad superada (''||v_usado_emp||'' / ''||v_capacidad_emp||'' GB)''; 
        END IF;
    ELSE
        :error := ''Usuario no válido'';
    END IF;
END;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'api',
      p_pattern            => 'equipos/registrar',
      p_method             => 'POST',
      p_name               => 'licencia',
      p_bind_variable_name => 'licencia',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'api',
      p_pattern            => 'equipos/registrar',
      p_method             => 'POST',
      p_name               => 'nombre',
      p_bind_variable_name => 'nombre',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'api',
      p_pattern            => 'equipos/registrar',
      p_method             => 'POST',
      p_name               => 'ip',
      p_bind_variable_name => 'ip',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'api',
      p_pattern            => 'equipos/registrar',
      p_method             => 'POST',
      p_name               => 'ubicacion',
      p_bind_variable_name => 'ubicacion',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'api',
      p_pattern            => 'equipos/registrar',
      p_method             => 'POST',
      p_name               => 'estado',
      p_bind_variable_name => 'estado',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'api',
      p_pattern            => 'equipos/registrar',
      p_method             => 'POST',
      p_name               => 'usado',
      p_bind_variable_name => 'usado',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'api',
      p_pattern            => 'equipos/registrar',
      p_method             => 'POST',
      p_name               => 'capacidad',
      p_bind_variable_name => 'capacidad',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'api',
      p_pattern            => 'equipos/registrar',
      p_method             => 'POST',
      p_name               => 'email',
      p_bind_variable_name => 'email',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'api',
      p_pattern            => 'equipos/registrar',
      p_method             => 'POST',
      p_name               => 'clave',
      p_bind_variable_name => 'clave',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'api',
      p_pattern            => 'equipos/registrar',
      p_method             => 'POST',
      p_name               => 'error',
      p_bind_variable_name => 'error',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'api',
      p_pattern            => 'equipos/registrar',
      p_method             => 'POST',
      p_name               => 'empresa',
      p_bind_variable_name => 'empresa',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'api',
      p_pattern            => 'equipos/registrar',
      p_method             => 'POST',
      p_name               => 'cargo',
      p_bind_variable_name => 'cargo',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'api',
      p_pattern            => 'equipos/registrar',
      p_method             => 'POST',
      p_name               => 'descripcion',
      p_bind_variable_name => 'descripcion',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'api',
      p_pattern        => 'equipos/actualizar',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'api',
      p_pattern        => 'equipos/actualizar',
      p_method         => 'PUT',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'DECLARE
    v_capacidad     number;
    v_capacidad_emp number;
    v_emp_id        number;
    v_usado_emp     number;
BEGIN
    -- Comprobar capacidad de equipo
    select nvl(equ_capacidad,emp_capacidad), emp_capacidad, emp_id into v_capacidad, v_capacidad_emp, v_emp_id
    from equipos, empresas
    where equ_emp = emp_id
        and equ_licencia = :licencia;
    
    -- Comprobar capacidad de empresa
    select nvl(sum(nvl(equ_usado,0)),0) + nvl(:usado,0) into v_usado_emp
    from equipos
    where equ_emp = v_emp_id;

    IF nvl(:usado,0) <= v_capacidad AND v_usado_emp <= v_capacidad_emp THEN
        update equipos
        set
            EQU_NOMBRE      = NVL(:nombre, EQU_NOMBRE),
            EQU_IP          = NVL(:ip, EQU_IP),
            EQU_UBICACION   = NVL(:ubicacion, EQU_UBICACION),
            EQU_CARGO       = NVL(:cargo, EQU_CARGO),
            EQU_DESCRIPCION = NVL(:descripcion, EQU_DESCRIPCION),
            EQU_ACTIVO      = NVL(:activo, EQU_ACTIVO),
            EQU_ESTADO      = NVL(:estado, EQU_ESTADO),
            EQU_USADO       = NVL(:usado, EQU_USADO),
            EQU_CAPACIDAD   = NVL(:capacidad, EQU_CAPACIDAD)
        where equ_licencia = :licencia;
    ELSE
        :error := ''Supera la capacidad máxima (''||v_usado_emp||'' / ''||v_capacidad_emp||'' GB)'';
    END IF;
    
END;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'api',
      p_pattern            => 'equipos/actualizar',
      p_method             => 'PUT',
      p_name               => 'estado',
      p_bind_variable_name => 'estado',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'api',
      p_pattern            => 'equipos/actualizar',
      p_method             => 'PUT',
      p_name               => 'usado',
      p_bind_variable_name => 'usado',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'api',
      p_pattern            => 'equipos/actualizar',
      p_method             => 'PUT',
      p_name               => 'licencia',
      p_bind_variable_name => 'licencia',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'api',
      p_pattern            => 'equipos/actualizar',
      p_method             => 'PUT',
      p_name               => 'error',
      p_bind_variable_name => 'error',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'api',
      p_pattern            => 'equipos/actualizar',
      p_method             => 'PUT',
      p_name               => 'nombre',
      p_bind_variable_name => 'nombre',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'api',
      p_pattern            => 'equipos/actualizar',
      p_method             => 'PUT',
      p_name               => 'ip',
      p_bind_variable_name => 'ip',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'api',
      p_pattern            => 'equipos/actualizar',
      p_method             => 'PUT',
      p_name               => 'ubicacion',
      p_bind_variable_name => 'ubicacion',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'api',
      p_pattern            => 'equipos/actualizar',
      p_method             => 'PUT',
      p_name               => 'activo',
      p_bind_variable_name => 'activo',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'api',
      p_pattern            => 'equipos/actualizar',
      p_method             => 'PUT',
      p_name               => 'capacidad',
      p_bind_variable_name => 'capacidad',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'api',
      p_pattern            => 'equipos/actualizar',
      p_method             => 'PUT',
      p_name               => 'cargo',
      p_bind_variable_name => 'cargo',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'api',
      p_pattern            => 'equipos/actualizar',
      p_method             => 'PUT',
      p_name               => 'descripcion',
      p_bind_variable_name => 'descripcion',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

        
COMMIT;

END;